# Generated by Django 3.2.4 on 2021-06-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_upload_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
