# Generated by Django 3.2.4 on 2021-07-30 17:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210728_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='json_data',
            field=jsonfield.fields.JSONField(default=[{'pos': {'height': 160, 'width': 105, 'x': 696, 'y': 235}, 'subtype': 38, 'type': 'anatomy'}, {'pos': {'height': 185, 'width': 130, 'x': 727, 'y': 339}, 'subtype': 38, 'type': 'anatomy'}, {'pos': {'height': 208, 'width': 102, 'x': 825, 'y': 353}, 'subtype': 30, 'type': 'treatment'}], null=True),
        ),
    ]
