# Generated by Django 3.2.4 on 2021-07-30 21:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_upload_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='json_data',
            field=jsonfield.fields.JSONField(default=[{'pos': {'height': 160, 'width': 105, 'x': 696, 'y': 235}, 'subtype': 38, 'type': 'anatomy'}, {'pos': {'height': 185, 'width': 130, 'x': 727, 'y': 339}, 'subtype': 38, 'type': 'anatomy'}], null=True),
        ),
    ]
